package xy.onlasdan.galery.crypto

import android.content.Context
import android.util.SparseArray
import ca.pkay.rcloneexplorer.RcloneRcd
import ca.pkay.rcloneexplorer.util.FLog
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit

/**
 * Wraps RcloneRcd to upload/download/list/delete files via a rclone crypt remote.
 *
 * Requires a rclone.conf with a crypt remote named "galery" configured.
 * The conf is generated by [setupCryptRemote] using keys from [CryptKeyStore].
 */
class RcloneCryptProvider(private val context: Context) : RcloneRcd.JobsUpdateHandler {

    private val TAG = "RcloneCryptProvider"
    private var rcd: RcloneRcd? = null

    override fun onRcdJobsUpdate(status: SparseArray<RcloneRcd.JobStatusResponse>) {
        // Handle job updates if needed
    }

    fun initRcd() {
        if (rcd == null) {
            rcd = RcloneRcd(context, this)
        }
        rcd?.startRcd()
    }

    fun stopRcd() {
        rcd?.stopRcd()
        rcd = null
    }

    fun setupCryptRemote(password: String, salt: String) {
        val keys = CryptKeyStore(context)
        keys.save(password, salt)

        val params = HashMap<String, String>()
        params["type"] = "crypt"
        params["password"] = password
        params["salt"] = salt
        params["filename_encryption"] = "standard"
        params["directory_name_encryption"] = "true"

        rcd?.createConfig("galery", "crypt", params)
    }

    fun isConfigured(): Boolean {
        val keys = CryptKeyStore(context)
        return keys.isConfigured() && rcd?.isAlive == true
    }

    suspend fun upload(localPath: File, remotePath: String): Boolean = withContext(Dispatchers.IO) {
        try {
            val latch = CountDownLatch(1)
            var success = false

            rcd?.copyFile("local", localPath.absolutePath, "galery", remotePath, object : RcloneRcd.JobStatusHandler {
                override fun handleJobStatus(jobStatusResponse: RcloneRcd.JobStatusResponse) {
                    if (jobStatusResponse.finished) {
                        success = jobStatusResponse.success
                        latch.countDown()
                    }
                }
            })

            latch.await(5, TimeUnit.MINUTES)
            success
        } catch (e: Exception) {
            FLog.e(TAG, "Upload failed: ${e.message}")
            false
        }
    }

    suspend fun download(remotePath: String, localPath: File): Boolean = withContext(Dispatchers.IO) {
        try {
            val latch = CountDownLatch(1)
            var success = false

            rcd?.copyFile("galery", remotePath, "local", localPath.absolutePath, object : RcloneRcd.JobStatusHandler {
                override fun handleJobStatus(jobStatusResponse: RcloneRcd.JobStatusResponse) {
                    if (jobStatusResponse.finished) {
                        success = jobStatusResponse.success
                        latch.countDown()
                    }
                }
            })

            latch.await(5, TimeUnit.MINUTES)
            success
        } catch (e: Exception) {
            FLog.e(TAG, "Download failed: ${e.message}")
            false
        }
    }

    suspend fun list(remotePath: String): List<String> = withContext(Dispatchers.IO) {
        try {
            val items = rcd?.list("galery", remotePath)
            items?.map { it.name } ?: emptyList()
        } catch (e: Exception) {
            FLog.e(TAG, "List failed: ${e.message}")
            emptyList()
        }
    }

    suspend fun delete(remotePath: String): Boolean = withContext(Dispatchers.IO) {
        try {
            val latch = CountDownLatch(1)
            var success = false

            rcd?.deleteFile("galery", remotePath, object : RcloneRcd.JobStatusHandler {
                override fun handleJobStatus(jobStatusResponse: RcloneRcd.JobStatusResponse) {
                    if (jobStatusResponse.finished) {
                        success = jobStatusResponse.success
                        latch.countDown()
                    }
                }
            })

            latch.await(5, TimeUnit.MINUTES)
            success
        } catch (e: Exception) {
            FLog.e(TAG, "Delete failed: ${e.message}")
            false
        }
    }

    suspend fun mkdir(remotePath: String): Boolean = withContext(Dispatchers.IO) {
        try {
            rcd?.mkDir("galery", remotePath)
            true
        } catch (e: Exception) {
            FLog.e(TAG, "Mkdir failed: ${e.message}")
            false
        }
    }
}
