package xy.onlasdan.galery.crypto

import android.content.Context
import android.util.SparseArray
import ca.pkay.rcloneexplorer.RcloneRcd
import ca.pkay.rcloneexplorer.Services.RcdService
import ca.pkay.rcloneexplorer.util.FLog
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit

/**
 * Wraps RcloneRcd to upload/download/list/delete files via a rclone crypt remote.
 *
 * Requires a rclone.conf with a crypt remote named "galery" configured.
 * The conf is generated by [setupCryptRemote] using keys from [CryptKeyStore].
 */
class RcloneCryptProvider(private val context: Context) : RcloneRcd.JobsUpdateHandler {

    private val TAG = "RcloneCryptProvider"
    private var rcd: RcloneRcd? = null

    override fun onRcdJobsUpdate(status: SparseArray<RcloneRcd.JobStatusResponse>) {
        // Handle job updates if needed
    }

    /**
     * Initialize the rclone RCD daemon. Must be called before any operations.
     */
    fun initRcd() {
        if (rcd == null) {
            rcd = RcloneRcd(context, this)
        }
        rcd?.startRcd()
    }

    /**
     * Stop the rclone RCD daemon.
     */
    fun stopRcd() {
        rcd?.stopRcd()
        rcd = null
    }

    /**
     * Create the crypt remote configuration in rclone.conf.
     */
    fun setupCryptRemote(password: String, salt: String) {
        val keys = CryptKeyStore(context)
        keys.save(password, salt)

        // Create the crypt remote via rclone API
        val params = HashMap<String, String>()
        params["type"] = "crypt"
        params["password"] = password
        params["salt"] = salt
        params["filename_encryption"] = "standard"
        params["directory_name_encryption"] = "true"

        rcd?.createConfig("galery", "crypt", params)
    }

    /**
     * Check if rclone is configured and ready.
     */
    fun isConfigured(): Boolean {
        val keys = CryptKeyStore(context)
        return keys.isConfigured() && rcd?.isAlive == true
    }

    /**
     * Upload a file to the encrypted remote.
     * Uses rclone copyFile to copy local file to remote.
     */
    suspend fun upload(localPath: File, remotePath: String): Boolean = withContext(Dispatchers.IO) {
        try {
            val latch = CountDownLatch(1)
            var success = false

            rcd?.copyFile("local", localPath.absolutePath, "galery", remotePath, object : RcloneRcd.JobStatusHandler {
                override fun onJobStatusUpdate(jobId: Int, status: RcloneRcd.JobStatusResponse) {
                    // Job completed or errored
                    if (status.finished) {
                        success = status.success
                        latch.countDown()
                    }
                }

                override fun onJobFinished(jobId: Int) {
                    latch.countDown()
                }
            })

            latch.await(5, TimeUnit.MINUTES)
            success
        } catch (e: Exception) {
            FLog.e(TAG, "Upload failed: ${e.message}")
            false
        }
    }

    /**
     * Download a file from the encrypted remote.
     * Uses rclone copyFile to copy remote file to local.
     */
    suspend fun download(remotePath: String, localPath: File): Boolean = withContext(Dispatchers.IO) {
        try {
            val latch = CountDownLatch(1)
            var success = false

            rcd?.copyFile("galery", remotePath, "local", localPath.absolutePath, object : RcloneRcd.JobStatusHandler {
                override fun onJobStatusUpdate(jobId: Int, status: RcloneRcd.JobStatusResponse) {
                    if (status.finished) {
                        success = status.success
                        latch.countDown()
                    }
                }

                override fun onJobFinished(jobId: Int) {
                    latch.countDown()
                }
            })

            latch.await(5, TimeUnit.MINUTES)
            success
        } catch (e: Exception) {
            FLog.e(TAG, "Download failed: ${e.message}")
            false
        }
    }

    /**
     * List files in a remote directory.
     * Returns list of file/directory names.
     */
    suspend fun list(remotePath: String): List<String> = withContext(Dispatchers.IO) {
        try {
            val items = rcd?.list("galery", remotePath)
            items?.map { it.name } ?: emptyList()
        } catch (e: Exception) {
            FLog.e(TAG, "List failed: ${e.message}")
            emptyList()
        }
    }

    /**
     * Delete a file from the encrypted remote.
     */
    suspend fun delete(remotePath: String): Boolean = withContext(Dispatchers.IO) {
        try {
            val latch = CountDownLatch(1)
            var success = false

            rcd?.deleteFile("galery", remotePath, object : RcloneRcd.JobStatusHandler {
                override fun onJobStatusUpdate(jobId: Int, status: RcloneRcd.JobStatusResponse) {
                    if (status.finished) {
                        success = status.success
                        latch.countDown()
                    }
                }

                override fun onJobFinished(jobId: Int) {
                    latch.countDown()
                }
            })

            latch.await(5, TimeUnit.MINUTES)
            success
        } catch (e: Exception) {
            FLog.e(TAG, "Delete failed: ${e.message}")
            false
        }
    }

    /**
     * Create a directory in the encrypted remote.
     */
    suspend fun mkdir(remotePath: String): Boolean = withContext(Dispatchers.IO) {
        try {
            rcd?.mkDir("galery", remotePath)
            true
        } catch (e: Exception) {
            FLog.e(TAG, "Mkdir failed: ${e.message}")
            false
        }
    }
}
